### ISSUE TITLE
Add individual ratings fields as global fields

### ISSUE THREAD

**Issue by Thiousi** [jenstornell/kirby-ratings#2]
This may make sense ?

**Comment by jenstornell** [comment]
You mean like in the global site content file, controlled by the panel?

I'm a little lost in what you mean. Maybe you can explain it more? Sorry... it's friday afternoon. ;)

**Comment by Thiousi** [comment]
Your ratings field is stored in the blueprints/fields folder so that you can call it in a blueprint with:

```
ratings: ratings
```

You could do that for all fields too I think!

**Comment by jenstornell** [comment]
You mean also register it as a global field definition?

**Comment by Thiousi** [comment]
Yes that's what I mean

**Comment by jenstornell** [comment]
Added.
