### ISSUE TITLE
Document how to add a language

### ISSUE THREAD

**Issue by Thiousi** [jenstornell/kirby-ratings#3]
This is quite self-explanatory when you're familiar with custom language assets but not for everyone

**Comment by jenstornell** [comment]
If you know how to do this I'm missing a french translation. ;)

But yes, good point.

**Comment by Thiousi** [comment]
French added :) (it's a bit rough I'll see if it needs adjustment when used in a live environment)

**Comment by jenstornell** [comment]
I've added a `languages` docs page here:

https://github.com/jenstornell/kirby-ratings/blob/master/docs/languages.md

If you think it's incomplete you can add pull requests if you want.
