### ISSUE TITLE
Offer a version that works without javascript

### ISSUE THREAD

**Issue by Thiousi** [jenstornell/kirby-ratings#5]

**Comment by jenstornell** [comment]
That would be a complete rewrite. I'm not even using forms in this plugin. Just scratch the surface. I'm not sure of this one.

It's hard to even trigger a modal window without js.

**Comment by Thiousi** [comment]
I'm digging through the code and see that this is quite a big rewrite. Maybe keep it for later :gift:

**Comment by jenstornell** [comment]
I have come up with an idea of a solution to it but it's not very nice. It's to simply link to a route which contains a voting form. After submit, redirect to the page where you came from.

**Comment by jenstornell** [comment]
I was thinking more about it and I will not add it. Most people use javascript. I would also be a little bit simpler to hack. Now I can add secret codes, local storage, not post as a form etc. Nothing is super proof but at least keep most of the bots out.
